= Espacios de participación

Los espacios de participación definen los principales canales o vías de participación. Se muestran en el menú superior principal de la plataforma.

La lógica central de la estructura del Decidim es que los *componentes se combinan en espacios de participación*. Existen diferentes tipos de espacios (iniciativas, procesos, consultas y asambleas) y diferentes instancias dentro de cada tipo (un proceso de elecciones y otro de presupuestos participativos, un órgano de consejo de barrio y otro de trabajadores, una iniciativa para cambiar una ley y otra para incluir algo en el orden del día de un pleno, etc.).

== Procesos

Los procesos de participación requieren rellenar un formulario de *configuración* general con los siguientes campos: Título o nombre del proceso, nombre corto para la url, hashtag (sirve de referencia para la comunicación en redes sociales), descripción corta, descripción larga, imagen de portada, imagen de banner, fecha de comienzo y finalización, ámbito, grupo promotor (responsable del proceso participativo a nivel político, puede ser el ayuntamiento o un grupo formado por técnicos/políticos del ayuntamiento y asociaciones u otras entidades), a quién va dirigido, objeto del proceso de participación y estructura participativa. El proceso de participación permite incorporar *documentos adjuntos*.

Los procesos de participación están divididos en *fases* (p.e. 1. fase de información y convocatoria, 2. fase de diagnóstico, 3. fase de propuestas, 4. fase de priorización, 5. fase de decisión, 6. fase de evaluación y 7. fase de seguimiento de resultados). Cada fase incluye los siguientes campos de configuración: título, descripción, fecha de inicio, fecha fin.

En los procesos también se pueden mostrar *anuncios o textos destacados*, tanto en la portada como en el encabezado de cada componente (propuestas, debates, etc.). Se pueden configurar mensajes diferentes en función de la fase que se encuentra activa.

Un *configurador de procesos de participación* permite activar y desactivar fases y sus componentes de manera sencilla. El configurador de procesos de Decidim es una de sus funcionalidades más potentes, éste permite total flexibilidad en el diseño de los procesos participativos según las diferentes realidades y formas de participación ciudadana.

La funcionalidad de *grupos de procesos* permite agrupar varios procesos, por ejemplo para Presupuestos Participativos de distritos o barrios distintos.

Los procesos de participación pueden estar en uno de los siguientes *estados de proceso*: 0) publicado o no publicado, 1) abierto (ha comenzado), 2) cerrado (ha terminado el proceso de participación pero sus resultados están aún en vías de ejecución), 3) finalizado (tanto el proceso como sus resultados ya están terminados) y 4) futuro (aún no ha comenzado).

Es posible *marcar como destacado* un proceso (aumentando su visibilidad en la portada).

También hay la posibilidad de *copiar procesos de participación* desde el panel de administración. Esta funcionalidad permite diseñar procesos modelo y realizar una copia de los mismos para configurar algunos detalles de los nuevos procesos y no tener que crearlos de la nada.

== Asambleas

Decidim permite la *creación y configuración* de *asambleas* de participación o gobierno (órganos de gobierno, de participación, consejos, grupos de trabajo, etc.), entendidos como grupos estructurados de participantes que, a título individual o representativo, se reúnen periódicamente, con la capacidad de crear propuestas y tomar decisiones.

La *sección de asambleas* permite ver un listado completo de todos las asambleas que se activan y configuran desde el panel de administración. La *configuración* básica exige determinar para cada órgano los siguientes campos: nombre, imagen, ámbito (global, territorial o sectorial), función del órgano (objeto de actuación), tipo de órgano (gobierno, ejecutivo, consultivo / asesor, participativo, grupo de trabajo, comisión,...), fecha de creación, creado por iniciativa de (Ayuntamiento, ciudadanos u otros), duración (indefinida o determinada, en este caso, fecha de finalización), fecha de inclusión en el Decidim, fecha de cierre y motivo, cómo se organiza (funciones, competencias,...), composición, si es posible adherirse y cómo hacerlo, la forma de selección los miembros, tipo/ función de los miembros dentro del órgano, composición de grupos de trabajos internos como comisión de seguimiento o comisión asesora), características del órgano, redes sociales del órgano (nombre de la red social y enlace), y próximos encuentros del órgano.

* *Convocatorias de reuniones*: envío automático de convocatoria, creación colaborativa del orden del día, inscripción a asistencia. Para un listado completo de funcionalidades ver componente "encuentros" [funcionalidad prevista para 2017Q2-3, AjB-Lote2Mod2].
* *Características de la asamblea*: abierta, pública, transparente, u otras características del grado de participación que la asamblea permite.
* *Composición*: permite definir la composición del órgano con más detalle, haciendo uso de los perfiles de participantes asociados al órgano así como otras característicasSe genera automáticamente una visualización de la composición del órgano a partir de la composición de los miembros participantes [funcionalidad prevista para 2018Q2-3, AjB-Lote2Mod3]:
** *Tipos de miembros*: Presidente, vicepresidente, secretarios, otros.
** *Origen de miembros*: por sorteo, elección directa, representación de otra asamblea, representación de gobierno, etc.
** *Grupos de trabajo interno*: creación de sub-asambleas. Los grupos de trabajo, se podrán relacionar con el órgano al que pertenecen.
** *Características*: abierto/cerrado, transparente, con diferentes permisos de acceso.
* *Visualización*: permite visualizar datos internos de cada órgano así como relaciones entre asambleas [funcionalidad prevista para 2018Q2-3, AjB-Lote2Mod3].
** *Composición*: muestra en forma de diagrama circular la composición del órgano.
** *Organigramas*: muestra la jerarquía o red de asambleas y sus relaciones.
* *Mapa y calendario*: permite ver la localización de todos las asambleas en un mapa y en un calendario [funcionalidad prevista para 2018Q3-4, AjB-Lote2Mod3].
* *Relación con otros espacios y componentes*
** *Relación con procesos*: las asambleas pueden ser grupo promotor, iniciar un proceso o realizar propuestas dentro de un proceso. La composición de un órgano tiene que poder ser el resultado de un proceso (de elección de cargos) [funcionalidad prevista para 2018Q2-3, AjB-Lote2Mod3].
** *Propuestas y resultados*: un órgano puede generar sus propias propuestas o resultados.
*** Se muestra la manera en que la propuesta fue acordada (por consenso, mayoría, número de votos, etc.) [funcionalidad prevista para 2018Q2-3, AjB-Lote2Mod3].
** *Encuentros*: las asambleas tendrán una lista asociada de encuentros, pero algunas funcionalidades pueden saltar de un encuentro al siguiente, como las iniciativas ciudadanas de inclusión de un punto en el orden del día. Igualmente las actas deben de poderse mostrar independientemente del encuentro, como asociadas directamente al órgano [funcionalidad prevista para 2018Q2-3, AjB-Lote2Mod3].

== Iniciativas

Este espacio de participación permite a la ciudadanía hacer propuestas y recoger el *número de firmas y/o apoyos requeridos* según su tipología (los diferentes tipos están definidos en el reglamento municipal), dando lugar al inicio del procedimiento administrativo para su tramitación y seguimiento ciudadano.

El funcionamiento de las iniciativas es el siguiente:

* Cualquier persona o entidad ciudadana verificada puede crear una propuesta de iniciativa ciudadana. Hay *diferentes tipos de iniciativas* con diferentes número de apoyos/firmas requeridos para su tramitación (todas ellas configurables). Desde la portada de creación de iniciativas se puede ver la descripción de cada una de las modalidades, el número de firmas requeridas y ejemplos (p.e. vídeos explicativos).
* Para evitar duplicidades, una vez creada una iniciativa el sistema presenta sugerencias de *iniciativas similares* antes de continuar con el siguiente paso. Una vez descartadas propuestas similares se muestra el formulario específico para cada tipo de iniciativa, con el número mínimo de apoyos requeridos. El creador dispone entonces de una URL para invitar a otras personas a sumarse y dar apoyo. También se muestra un mapa con los puntos físicos de recogida de firmas en caso de que las haya.
* Una vez recogido el número mínimo de apoyos, la iniciativa pasa a una fase de *moderación y validación técnica*, donde personal del Ayuntamiento puede realizar diferentes acciones (aprobarla, rechazarla o sugerir modificaciones).
* Se puede realizar el seguimiento de la iniciativa y *recibir notificaciones sobre actualizaciones* de estado, además la persona o grupo promotor de la misma puede enviar boletines periódicos informativos al resto de usuarios de la plataforma que hayan decidido hacer el seguimiento a la iniciativa.
* Al finalizar el período establecido una iniciativa puede tener dos estados posibles:
** *Rechazada*: en caso de no conseguir el número mínimo de firmas se muestra el mensaje "no reúne las firmas necesarias" y se notifica a su creador.
** *Aceptada*: en caso de haber conseguido las firmas o apoyos suficientes se acepta e inicia la tramitación correspondiente.

== Consultas

El espacio de consultas (votaciones a las que son llamadas todas las personas participantes de la organización sobre preguntas específicas) permite a los participantes *informarse de las consultas* futuras o en curso, *debatir* sobre el objeto de la consulta y realizar el *seguimiento* del resultado. También ofrece una *pasarela a un sistema de voto electrónico* externo a Decidim pero integrado en términos de interfaz y de gestión y verificación de identidades [Funcionalidad prevista para 2018Q2-3, AjB].
