= 4 Participantes

== 4.1 Registro y verificación

Cualquier visitante puede acceder a todo el contenido de la web directamente. Sin embargo para poder hacer propuestas o comentarios deben realizar un *registro*. El registro se puede hacer *directamente* en la plataforma o mediante pasarelas con otras *redes sociales* (Facebook, Twitter o Google+). El registro directo exige asociar una cuenta de correo electrónico y una contraseña a la cuenta de usuario/a.

Las funcionalidades orientadas a la decisión (apoyos, votos, etc.) requieren *verificación*. El principal sistema de verificación es contra el padrón municipal u otra base de datos de personas registradas con las que Decidim se comunica vía API. También se puede verificar *vía SMS*, o con un *código* especial enviado por carta u otros medios, y desde el panel de administración se puede *veri****ficar manualmente* a una persona participante [funcionalidades previstas para 2018Q1-3, AjB-Lote1].

Además de la verificación, las personas participantes pueden solicitar *oficializar* su nombre de usuaria/o. A partir de la oficialización su nombre de usuaria/o aparecerá con un símbolo que permite reconocer a terceros que ese nombre de usuaria/o corresponde a quien dice ser.

*Asociaciones u organizaciones* cuya identidad pueda verificarse de algún modo también pueden registrarse y verificarse. La verificación dará automáticamente estatus de oficialización.

== 4.2 Registro público de actividad de administración

La verificación manual de participantes, así como otras acciones de administración, introducen vulnerabilidad o posibilidades de usos perversos por parte de las personas administradoras de la plataforma. Para ello Decidim incluye un *registro público de las actividades de administración* para poder auditar de manera pública y transparente dichas acciones.

== 4.3 Perfil de usuario y configuración personal

Existe una *página de perfil de usuario* en la que las personas participantes pueden realizar *modificaciones de sus datos* (como la cuenta de correo electrónico, contraseña, etc.), subir y habilitar una imagen de *avatar*, configurar las notificaciones, y darse de baja.

La página de perfil de usuario permite también a participantes definir su *perfil enriquecido* de intereses y habilidades, de manera voluntaria y escogiendo el grado de visibilidad de dicha información. Esto permite recibir notificaciones personalizadas o el matching para colaboraciones [funcionalidad prevista para 2018Q1-3, AjB-Lote1].

== 4.4 Seguimiento y notificaciones

Las personas participantes reciben *notificaciones automáticas* de los contenidos que han creado: respuestas a comentarios y comentarios a sus propuestas, así como de los resultados de sus propuestas (si han sido aceptadas o rechazadas).

Además de las notificaciones automáticas una persona participante puede decidir *seguir cualquier elemento* del sistema (otras propuestas, resultados, procesos, asambleas, iniciativas, grupos o usuarios, etc.) y recibir notificaciones [funcionalidad prevista para 2017Q3, GenCat].

== 4.5 Comunicación entre participantes

Es posible enviar *mensajes directos* a participantes a través de la plataforma, recibiendo una notificación por correo electrónico [funcionalidad prevista para 2017Q3, AjB].

También se pueden realizar *menciones* (en los comentarios) a cualquier usuaria/o registrada/o y recibirá automáticamente una notificación. [funcionalidad prevista para 2018Q1-3, AjB-Lote1].

== 4.6 Engagement

Decidim cuenta con una serie de funcionalidades orientadas a _gamificar_ la plataforma, con el objetivo de *atraer y mantener interesadas a un número creciente de participantes*, así como promover prácticas que potencien la calidad democrática y la inteligencia colectiva en la participación [el sistema de gamificación está previsto para 2018Q1-3, AjB-Lote1].

El sistema de gamificación Incluye dos modalidades, una centrada en las personas usuarias y otra centrada en las propuestas.

* La modalidad *centrada en los usuarios* incorpora un *sistema de puntos* basados en diferentes criterios (grado de detalle de su perfil de usuario, número de invitaciones a otras personas a la plataforma, número de propuestas realizadas y comentadas, número de comentarios, número de apoyos obtenidos, número de seguidores, etc.)

La combinación de éstos y otros indicadores sirve para generar recorridos de gamificación para cada usuario y definir hitos como: persona más participativa del distrito, liderazgo en debates, etc.

* La gamificación *centrada en propuestas/iniciativas* permite a sus promotores, firmantes y seguidores dinamizar la interacción con las mismas incorporando algunas *métricas* (número de veces que la propuesta es compartida en redes sociales, grado de controversia (número de comentarios positivos y negativos), calidad de la deliberación (profundidad del árbol de comentarios), cantidad de visitas recibidas, etc.

== 4.7 Grupos de usuarios

Las personas participantes pueden registrarse en la plataforma como miembros de una o varias organizaciones/colectivos. Una vez verificada la organización y la condición de miembro, la participante puede realizar acciones (hacer propuestas, realizar comentarios, etc.) con su nombre de usuaria/o o con el nombre de la organización. [Funcionalidad prevista para 2018Q1-3, AjB-Lote1]

Los grupos de usuarios también pueden gestionar permisos de usuario y administración asignados a grupos, así como espacios de debate privados o compartir información entre el grupo de usuarios, por ejemplo, que asistió a un encuentro presencial. [Funcionalidad prevista para 2018Q1-3, AjB-Lote1]
