= Espais de participació
include::translations::partial$attributes.adoc[]

Els espais de participació defineixen els canals o vies de participació principals. Es mostren al menú superior principal de la plataforma.

La lògica central de l'estructura del Decidim és que els *components es combinen en espais de participació*. Existeixen diferents tipus d'espais (iniciatives, processos, consultes i assemblees) i diferents instàncies dins de cada tipus (un procés d'eleccions i un altre de pressupostos participatius, un òrgan de consell de barri i un altre de treballadors, una iniciativa per canviar una llei i una altra per incloure alguna cosa en l'ordre del dia d'un ple, etcètera).

== Processos

Els processos de participació requereixen omplir un formulari de *configuració* general amb els camps següents: Títol o nom del procés, nom curt per a l'URL, etiqueta (_hashtag_, serveix de referència per a la comunicació en xarxes socials), descripció curta, descripció llarga, imatge de portada, imatge de bàner, data de començament i acabament, àmbit, grup promotor (responsable del procés participatiu en l’àmbit polític, pot ser l'ajuntament o un grup format per tècnics/polítics de l'ajuntament i associacions o altres entitats), a qui va dirigit, objecte del procés de participació i estructura participativa. El procés de participació permet incorporar *documents adjunts*.

Els processos de participació estan dividits en *fases* (p. ex. 1. fase d'informació i convocatòria, 2. fase de diagnòstic, 3. fase de propostes, 4. fase de priorització, 5. fase de decisió, 6. fase d'avaluació i 7. fase de seguiment de resultats). Cada fase inclou els següents camps de configuració: títol, descripció, data d'inici, data fi.

En els processos també es poden mostrar *anuncis o textos destacats*, tant en la portada com en l'encapçalament de cada component (propostes, debats, etcètera). Es poden configurar missatges diferents en funció de la fase que es troba activa.

Un *configurador de processos de participació* permet activar i desactivar fases i els seus components de manera senzilla. El configurador de processos de Decidim és una de les seves funcionalitats més potents, aquest permet total flexibilitat en el disseny dels processos participatius segons les diferents realitats i formes de participació ciutadana.

La funcionalitat de **grups de processos **permet agrupar diversos processos, per exemple per a pressupostos participatius de districtes o barris diferents.

Els processos de participació poden estar en un dels *estats de procés* següents: 0) publicat o no publicat, 1) obert (ha començat), 2) tancat (ha acabat el procés de participació però els seus resultats són encara en via d'execució), 3) finalitzat (tant el procés com els seus resultats ja estan acabats) i 4) futur (encara no ha començat).

És possible **marcar com destacat **un procés (augmentant-ne la visibilitat a la portada).

També hi ha la possibilitat de *copiar processos de participació* des del tauler d'administració. Aquesta funcionalitat permet dissenyar processos model i fer-ne una còpia per configurar alguns detalls dels nous processos i no haver de crear-los del no-res.

== Assemblees

Decidim permet la *creació i configuració d'assemblees* de participació o govern (òrgans de govern, de participació, consells, grups de treball, etcètera), entesos com a grups estructurats de participants que, a títol individual o representatiu, es reuneixen periòdicament, amb la capacitat de crear propostes i prendre decisions.

La *secció d'assemblees* permet veure un llistat complet de totes les assemblees que s'activen i es configuren des del tauler d'administració. La *configuració* bàsica exigeix determinar, per a cada òrgan, els camps següents: nom, imatge, àmbit (global, territorial o sectorial), funció de l'òrgan (objecte d'actuació), tipus d'òrgan (govern, executiu, consultiu/assessor, participatiu, grup de treball, comissió...), data de creació, creat per iniciativa de (Ajuntament, ciutadans o altres), durada (indefinida o determinada; en aquest cas, data d'acabament), data d'inclusió en el Decidim, data de tancament i motiu, com s'organitza (funcions, competències...), composició, si és possible adherir-s’hi i com fer-ho, la forma de selecció els membres, tipus/funció dels membres dins de l'òrgan, composició de grups de treball interns com a comissió de seguiment o comissió assessora), característiques de l'òrgan, xarxes socials de l'òrgan (nom de la xarxa social i enllaç), i properes trobades de l'òrgan.

* *Convocatòries de reunions*: tramesa automàtica de convocatòria, creació col·laborativa de l'ordre del dia, inscripció a assistència. Per a un llistat complet de funcionalitats, vegeu el component "trobades" [funcionalitat prevista per a 2018Q2-3, AjB-Lot2Mod2].
* *Característiques de l'assemblea*: oberta, pública, transparent, o altres característiques del grau de participació que permet l'assemblea.
* *Composició*: Permet definir la composició de l'òrgan amb més detall, fent ús dels perfils de participants associats a l'òrgan així com altres característiques. Es genera automàticament una visualització de la composició de l'òrgan a partir de la composició dels membres participants [funcionalitat prevista per a 2018Q2-3, AjB-Lot2Mod3]:
** *Tipus de membres*: President, vicepresident, secretaris, d'altres
** *Origen de membres*: per sorteig, elecció directa, representació d'una altra assemblea, representació de govern, etcètera.
** *Grups de treball intern*: creació de subassemblees. Els grups de treball es podran relacionar amb l'òrgan a què pertanyen.
** *Característiques*: Obert/tancat, transparent, amb diferents permisos d'accés.
* *Visualització*: permet visualitzar dades internes de cada òrgan, així com relacions entre assemblees [funcionalitat prevista per a 2018Q2-3, AjB-Lot2Mod3]
** *Composició*: mostra en forma de diagrama circular la composició de l'òrgan.
** *Organigrames*: mostra la jerarquia o xarxa d'assemblees i les seves relacions.
* *Mapa i calendari*: permet veure la localització de tots les assemblees en un mapa i en un calendari [funcionalitat prevista per a 2018Q3-4, AjB-Lot2Mod3].
* *Relació amb altres espais i components*
** *Relació amb processos*: les assemblees poden ser grup promotor, iniciar un procés o fer propostes dins d'un procés. La composició d'un òrgan ha de poder ser el resultat d'un procés (d'elecció de càrrecs) [funcionalitat prevista per a 2018Q2-3, AjB-Lot2Mod3]
** *Propostes i resultats*: un òrgan pot generar les seves pròpies propostes o resultats.
*** Es mostra la manera en què la proposta va ser acordada (per consens, majoria, nombre de vots, etcètera). [funcionalitat prevista per a 2018Q2-3, AjB-Lot2Mod3]
** *Trobades*: les assemblees tindran una llista associada de trobades, però algunes funcionalitats poden saltar d'una trobada al següent, com les iniciatives ciutadanes d'inclusió d'un punt en l'ordre del dia. Igualment les actes han de poder mostrar-se independentment de la trobada, com associades directament a l'òrgan [funcionalitat prevista per a 2018Q2-3, AjB-Lot2Mod3].

== Iniciatives

Aquest espai de participació permet a la ciutadania fer propostes i recollir el *nombre de signatures i suports requerits* segons la seva tipologia (els diferents tipus estan definits al reglament municipal), donant lloc a l'inici del procediment administratiu per a la seva tramitació i seguiment ciutadà.

El funcionament de les iniciatives és el següent:

* Qualsevol persona o entitat ciutadana verificada pot crear una proposta d'iniciativa ciutadana. Hi ha *diferents tipus d'iniciatives* amb diferent nombre de suports/signatures requerits per a la seva tramitació (totes elles configurables). Des de la portada de creació d'iniciatives es pot veure la descripció de cada una de les modalitats, el nombre de signatures requerides i exemples (p. ex. vídeos explicatius).
* Per evitar duplicitats, una vegada creada una iniciativa el sistema presenta suggeriments *d'iniciatives similars* abans de continuar amb el pas següent. Una vegada descartades propostes similars es mostra el formulari específic per a cada tipus d'iniciativa, amb el nombre mínim de suports requerits. El creador disposa llavors d'una URL per convidar altres persones a sumar-s’hi i donar-hi suport. També es mostra un mapa amb els punts físics de recollida de signatures en cas que n'hi hagi.
* Una vegada recollit el nombre mínim de suports, la iniciativa passa a una fase de *moderació i validació tècnica*, on personal de l'Ajuntament pot realitzar diferents accions (aprovar-la, rebutjar-la o suggerir modificacions).
* Es pot fer el seguiment de la iniciativa i *rebre notificacions sobre actualitzacions* d'estat, a més la persona o grup promotor de la mateixa pot enviar butlletins periòdics informatius a la resta d'usuaris de la plataforma que hagin decidit fer el seguiment a la iniciativa.
* Quan s’acaba el període establert, una iniciativa pot tenir dos estats possibles:
** *Rebutjada*: en cas de no aconseguir el nombre mínim de signatures es mostra el missatge "no reuneix les signatures necessàries" i es notifica al seu creador.
** *Acceptada*: en cas d'haver aconseguit les signatures o suports suficients s'accepta i s’inicia la tramitació corresponent.

== Consultes

L'espai de consultes (votacions a les quals són cridades totes les persones participants de l'organització sobre preguntes específiques) permet als participants** informar-se de les consultes** futures o en curs, *debatre* sobre l'objecte de la consulta i fer el *seguiment* del resultat. També ofereix una *passarel·la a un sistema de vot electrònic* extern a Decidim però integrat en termes d'interfície i de gestió i verificació d'identitats [Funcionalitat prevista per a 2018Q2-3, AjB].
